#!/usr/bin/env python
"""Regenerate dist/webapp/samples.js: the gold feedback sections for the
webapp 'Samples' menu.

Same deterministic pick as scripts/section_demo.py: 3-8 tagged paragraphs,
>=3 distinct OCM codes, one section per document (fallback tops up from
already-seen documents), shuffled with the given seed. Each sample carries
the work title (options label), the section title path, and the paragraph
texts (gold analyst-cleaned eHRAF text — not redistributable).
"""
import argparse
import json
import random
from collections import defaultdict
from pathlib import Path

ap = argparse.ArgumentParser()
ap.add_argument("--data", default="data/ethnographic_v5/val_docs.jsonl")
ap.add_argument("--out", default="dist/webapp/samples.js")
ap.add_argument("--sections", type=int, default=10)
ap.add_argument("--min-paras", type=int, default=3)
ap.add_argument("--max-paras", type=int, default=8)
ap.add_argument("--seed", type=int, default=0)
a = ap.parse_args()

recs = [json.loads(l) for l in open(a.data, encoding="utf-8")]

sections = defaultdict(list)
for di, d in enumerate(recs):
    for p in d["paragraphs"]:
        if p["tags"]:
            sections[(di, p.get("section", ""))].append(p)
cands = [(di, sec, ps) for (di, sec), ps in sections.items()
         if sec and sec not in ("Front matter", "Back matter")
         and a.min_paras <= len(ps) <= a.max_paras
         and len({c for p in ps for c, _ in p["tags"]}) >= 3]
rng = random.Random(a.seed)
rng.shuffle(cands)
picks, seen_docs = [], set()
for c in cands:
    if c[0] in seen_docs:
        continue
    seen_docs.add(c[0])
    picks.append(c)
    if len(picks) == a.sections:
        break
for c in cands:
    if len(picks) == a.sections:
        break
    if c not in picks:
        picks.append(c)

samples = [{"title": recs[di]["fields"].get("Title", recs[di]["hdoc"]),
            "section": sec, "paras": [p["text"] for p in ps]}
           for di, sec, ps in picks]

Path(a.out).write_text(
    "// Generated by scripts/make_samples.py — gold feedback sections "
    "(eHRAF-derived, do not redistribute).\n"
    "const SAMPLES = " + json.dumps(samples, ensure_ascii=False, indent=1) + ";\n",
    encoding="utf-8")
print(f"{len(samples)} sections -> {a.out}")
